services:
  - type: web
    name: claimsense
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GROQ_API_KEY
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://claimsense.onrender.com
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
